name: kid_demo
description: KID receiver demo app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+2

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ^3.3.9

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  receive_sharing_intent: ^1.4.5
  flutter_bloc: ^8.1.1
  encrypt: ^5.0.1
  path: ^1.8.2
  flutter_secure_storage: ^4.2.1
  freezed_annotation: ^2.2.0
  json_serializable: ^6.5.4
  path_provider: ^2.0.11
  intl: ^0.18.0
  share_plus: ^6.3.0
  barcode: ^2.2.3
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
