name: kid_demo
description: KID receiver demo app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.3.1

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ^3.3.9

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  receive_sharing_intent: ^1.4.5
  flutter_bloc: ^8.1.1
  encrypt: ^5.0.1
  path: ^1.8.2
  flutter_secure_storage: ^8.0.0
  freezed_annotation: ^2.2.0
  path_provider: ^2.0.11
  intl: ^0.18.0
  share_plus: ^6.3.0
  barcode: ^2.2.3
  flutter_svg: ^2.0.5
  dio: ^5.1.1
  retrofit: ^4.0.1
  get_it: ^7.3.0
  injectable: ^2.1.1
  json_annotation: ^4.8.0
  uuid: ^3.0.7
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  build_runner: ^2.3.3
  retrofit_generator: ^6.0.0+3
  json_serializable: ^6.5.4
  injectable_generator: ^2.1.5


flutter:
  uses-material-design: true
